import polars as pl

def mcc_schema():
    schema = {
        "PLACEMENT": pl.Utf8,
        "ACCOUNT NUMBER": pl.Utf8,
        "LAST_4_DIGITS_OF_CARD": pl.Int64,
        "DPD BUCKET": pl.Utf8,
        "DPD": pl.Int64,
        "MOBILE PROPER": pl.Utf8,
        "OB": pl.Float64,
        "FRESH/SPILLOVER": pl.Utf8,
        "RECEIVED DATE": pl.Date,
        "ENDO STATUS": pl.Utf8,
        "AS_OF": pl.Date,
        "CPM_ID": pl.Utf8,
        "APPLICATION_NUMBER": pl.Utf8,
        "APPLICATION_STATUS": pl.Utf8,
        "APPLICATION_CREATED_DATE": pl.Date,
        "CUSTOMER TYPE": pl.Utf8,
        "CUSTOMER BRACKET": pl.Utf8,
        "CUSTOMER CATEGORY": pl.Utf8,
        "FULL NAME": pl.Utf8,
        "FIRST_NAME": pl.Utf8,
        "LAST_NAME": pl.Utf8,
        "GENDER": pl.Utf8,
        "BIRTH_DATE": pl.Date,
        "MOBILE_NUMBER_1": pl.Utf8,
        "ALTERNATIVE_NUMBER": pl.Utf8,
        "EMAIL": pl.Utf8,
        "PRESENT_ADDRESS": pl.Utf8,
        "PERMANENT_ADDRESS": pl.Utf8,
        "SOURCE_OF_INCOME_DETAILS": pl.Utf8,
        "NATURE_OF_WORK": pl.Utf8,
        "EMPLOYMENT_DETAILS": pl.Utf8,
        "ID_TYPE": pl.Utf8,
        "ID_NUMBER": pl.Utf8,
        "CONTACT_REFERENCE_FULL_NAME": pl.Utf8,
        "CONTACT_REFERENCE_FIRST_NAME": pl.Utf8,
        "CONTACT_REFERENCE_LAST_NAME": pl.Utf8,
        "CONTACT_REFERENCE_RELATIONSHIP": pl.Utf8,
        "CONTACT_REFERENCE_MOBILE_NUMBER": pl.Utf8,
        "PRODUCT_ID": pl.Utf8,
        "PRODUCT_TYPE": pl.Utf8,
        "PRODUCT_NAME": pl.Utf8,
        "COHORT": pl.Utf8,
        "ACCOUNT_ID": pl.Utf8,
        "ACCOUNT_NUMBER": pl.Utf8,
        "LAST_4_DIGITS_OF_CARD": pl.Utf8,
        "ACCOUNT_STATE": pl.Utf8,
        "APPROVED_DATE": pl.Utf8,
        "BILLING_END_DATE": pl.Date,
        "DUE_DATE_PAST_DUE": pl.Date,
        "DUE_DATE_UPCOMING": pl.Date,
        "TENOR": pl.Utf8,
        "LAST_SET_TO_ARREARS_DATE": pl.Date,
        "PERFORMING": pl.Utf8,
        "DPD TIER": pl.Utf8,
        "VERTICAL_DPD": pl.Int64,
        "HORIZONTAL_DPD": pl.Int64,
        "LOAN CLASSIFICATION": pl.Utf8,
        "ECL STAGE": pl.Utf8,
        "LOAN AMOUNT": pl.Float64,
        "OVERLIMIT_%": pl.Float64,
        "OVERLIMIT_AMOUNT_USED": pl.Float64,
        "NET_LOAN_PROCEEDS": pl.Float64,
        "PRINCIPAL_OUTSTANDING": pl.Float64,
        "SERVICE_FEES_OUTSTANDING": pl.Utf8,
        "DST TYPE": pl.Utf8,
        "DST RATE": pl.Utf8,
        "CASH_ADVANCE_FEE_OUTSTANDING": pl.Utf8,
        "PENALTY_OUTSTANDING": pl.Utf8,
        "TOTAL_OUTSTANDING": pl.Float64,
        "TOTAL_CARD_STATEMENT_BALANCE": pl.Float64,
        "MINIMUM_AMOUNT_DUE": pl.Float64,
        "MINIMUM_AMOUNT_DUE_OUTSTANDING": pl.Float64,
        "DCA": pl.Utf8,
        "collections_segment": pl.Utf8,
        "tu_contact_number_1": pl.Utf8,
        "tu_contact_number_2": pl.Utf8,
        "tu_contact_number_3": pl.Utf8,
        "tu_contact_number_4": pl.Utf8,
        "tu_contact_number_5": pl.Utf8,
        "with_tu_min": pl.Utf8,
        "middle name": pl.Utf8,
        "FOR HIGH PRIO": pl.Utf8
    }
    return schema